Repository eilenshahbaz/LEAD-Center, pull requests merged in 2019-05, with the labels that each got.

#26 Interests tree questions
  db/seeds.rb
Labels: good first issue

#27 User Profile Update
  app/assets/images/cal-sunset-hero.jpg
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/home.scss
  app/assets/stylesheets/profile.scss
  app/controllers/profile_controller.rb
  app/models/user.rb
  app/views/profile/edit.html.erb
  app/views/profile/show.html.erb
  db/migrate/20190507225231_change_ethnicity_to_be_text_in_users.rb
  db/schema.rb
  db/seeds.rb
  features/profile_page.feature
  features/step_definitions/user_steps.rb
  spec/controllers/profile_controller_spec.rb
  spec/fixtures/users.yml
Labels: Needs Second Review

#25 Manually read interest
  .DS_Store
  .simplecov
  README.md
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/interests_controller.rb
  app/controllers/placeholder_controller.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/organization.rb
  app/views/interests/index.html.erb
  config/application.yml.asc
  config/routes.rb
  features/interests_upload.feature
  features/profile_page.feature
  features/step_definitions/user_steps.rb
  features/support/env.rb
  lib/interest.csv
  spec/controllers/interests_controller_spec.rb
  spec/fixtures/dummy.csv
  spec/models/organization_spec.rb
  spec/response/fake_interest.csv
  spec/response/raw_organizations_response_page1.txt
  spec/response/raw_organizations_response_page2.txt
Labels: LGTMFFTM

#36 Profile Page Fix
  app/assets/images/cal-sunset-hero.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/profile.scss
  app/controllers/profile_controller.rb
  app/models/user.rb
  app/views/profile/edit.html.erb
  app/views/profile/show.html.erb
  db/migrate/20190507225231_change_ethnicity_to_be_text_in_users.rb
  db/schema.rb
  db/seeds.rb
  features/profile_page.feature
  features/step_definitions/user_steps.rb
  spec/controllers/profile_controller_spec.rb
  spec/fixtures/users.yml
Labels: LGTMFFTM

#41 Golden pr update
  app/controllers/placeholder_controller.rb
  app/views/placeholder/home.html.erb
  app/views/placeholder/landing.html.erb
  app/views/profile/edit.html.erb
  app/views/profile/show.html.erb
  features/step_definitions/user_steps.rb
Labels: LGTMFFTM
